[package]
name = "m2_memory_server"
version = "0.1.0"
edition = "2024"

[dependencies]
mmap-rs = "0.6.0"
tokio = { version = "1", features = ["full"] }
rayon = "1.8"
memmap2 = "0.5.10"
lazy_static = "1.4"